import {
  User,
  Project,
  QATask,
  QABug,
  TestSuite,
  TestCase,
  DailyReport,
  RegressionCycle,
  Blocker,
  AuditLog,
  AppNotification,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@qa-aegis.com',
    role: 'qa_lead',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    experienceYears: 8,
    skills: ['Manual Testing', 'API Testing', 'Performance Testing', 'Security Testing', 'Regression Testing', 'Postman'],
    projectAllocations: [
      { projectId: 'prj-banking', percentage: 50 },
      { projectId: 'prj-mobile', percentage: 30 },
      { projectId: 'prj-merchant', percentage: 20 },
    ],
    onboardingCompleted: true,
  },
  {
    id: 'usr-hana',
    name: 'Hana Kim',
    email: 'hana.kim@qa-aegis.com',
    role: 'qa_engineer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    experienceYears: 3,
    skills: ['Manual Testing', 'API Testing', 'Mobile Testing', 'Web Testing', 'Postman', 'Regression Testing'],
    projectAllocations: [
      { projectId: 'prj-banking', percentage: 60 },
      { projectId: 'prj-mobile', percentage: 40 },
    ],
    onboardingCompleted: true,
    baselineContext: {
      currentWork: 'Payment Module API validation and Transfer feature test cases',
      mainTaskToday: 'Execute Payment API endpoint test suite and retest BUG-142',
      blockers: 'Staging API payment sandbox mock unavailable intermittently',
      expectedToday: 'Complete Payment API endpoints test suite',
      upcomingDeadlines: '2026-09-08 candidate freeze',
    },
  },
  {
    id: 'usr-ahmed',
    name: 'Ahmed Al-Mansoor',
    email: 'ahmed.mansoor@qa-aegis.com',
    role: 'qa_engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    experienceYears: 6,
    skills: ['Automation Testing', 'Playwright', 'Cypress', 'API Testing', 'Performance Testing', 'Regression Testing'],
    projectAllocations: [
      { projectId: 'prj-banking', percentage: 80 },
      { projectId: 'prj-merchant', percentage: 20 },
    ],
    onboardingCompleted: true,
    baselineContext: {
      currentWork: 'Banking SuperApp Login & Checkout full regression suite',
      mainTaskToday: 'Finish Login regression test cases and run Playwright smoke',
      blockers: 'High volume of regression modules and critical bug retests',
      expectedToday: 'Finish Login regression test suite execution',
      upcomingDeadlines: '2026-09-07 regression sign-off',
    },
  },
  {
    id: 'usr-sara',
    name: 'Sara Vance',
    email: 'sara.vance@qa-aegis.com',
    role: 'qa_engineer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    experienceYears: 4,
    skills: ['Web Testing', 'Database Testing', 'Manual Testing', 'API Testing', 'UAT'],
    projectAllocations: [
      { projectId: 'prj-mobile', percentage: 65 },
      { projectId: 'prj-merchant', percentage: 35 },
    ],
    onboardingCompleted: true,
    baselineContext: {
      currentWork: 'Mobile Banking biometric verification and Merchant onboarding UI',
      mainTaskToday: 'Execute 25 mobile test cases for virtual debit card flow',
      blockers: 'None currently',
      expectedToday: 'Finish virtual card test cases',
      upcomingDeadlines: '2026-09-10 sprint demo',
    },
  },
  {
    id: 'usr-daniel',
    name: 'Daniel Brody',
    email: 'daniel.brody@qa-aegis.com',
    role: 'qa_engineer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    experienceYears: 2,
    skills: ['Mobile Testing', 'Manual Testing', 'UI Testing'],
    projectAllocations: [{ projectId: 'prj-banking', percentage: 100 }],
    onboardingCompleted: true,
    baselineContext: {
      currentWork: 'End-to-End KYC Flow testing and Android 14 compatibility',
      mainTaskToday: 'Test 15 KYC edge cases and investigate BUG-140',
      blockers: 'Device farm timeout issues on Android 14 emulators',
      expectedToday: 'Complete KYC image upload validations',
      upcomingDeadlines: '2026-09-08 KYC milestone',
    },
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-banking',
    name: 'Banking SuperApp',
    description: 'Next-generation retail banking application with instant payments, multi-currency wallets, and biometric authentication.',
    status: 'Testing',
    startDate: '2026-08-01',
    targetReleaseDate: '2026-09-12',
    projectOwner: 'David Chen (VP Product)',
    qaLeadId: 'usr-sarah',
    memberIds: ['usr-hana', 'usr-ahmed', 'usr-daniel'],
    qaProgress: 74,
    regressionProgress: 62,
    resources: {
      prdTitle: 'PRD v2.4: Instant Wire Transfer & Biometric Core',
      prdUrl: 'https://docs.bankcorp.internal/prd/superapp-v2.4',
      prdContent: `# Product Requirements Document (PRD) - Banking SuperApp v2.4\n\n## 1. Overview & Objectives\nBanking SuperApp v2.4 introduces zero-latency peer-to-peer transfers with real-time biometric authorization. Target release date is September 12, 2026.\n\n## 2. Key Modules & Acceptance Criteria\n- **Module 1: Biometric Authorization (REQ-101)**\n  - FaceID / TouchID / Device Passcode fallback.\n  - Failures locked out after 3 attempts with 5-minute cool-off.\n- **Module 2: Instant Wire Transfer (REQ-102)**\n  - Idempotency key required on every POST /api/v2/transfers.\n  - Duplicate requests within 60s must return 409 Conflict with original transfer receipt.\n- **Module 3: Dynamic Fee Calculation (REQ-103)**\n  - Standard Tier: $1.50 per international wire.\n  - VIP Tier: $0.00 fee waiver.\n- **Module 4: Error Handling & Resilience (REQ-104)**\n  - In event of 504 Gateway Timeout from core banking ledger, transfer status remains PENDING_VERIFICATION, not FAILED, preventing double charges.\n\n## 3. QA Sign-Off Criteria\n- Zero Critical or High open defects.\n- 100% execution of P0/P1 regression suites.\n- Latency P99 under 450ms for transfer authorization.`,
      prdDocuments: [
        {
          id: 'doc-01',
          name: 'SuperApp_PRD_v2.4_Final.pdf',
          fileName: 'SuperApp_PRD_v2.4_Final.pdf',
          fileSize: '2.4 MB',
          uploadedBy: 'Sarah Jenkins',
          uploadedAt: '2026-08-10',
          version: 'v2.4',
          downloadUrl: '#',
        },
        {
          id: 'doc-02',
          name: 'Transfer_API_Swagger_Spec.docx',
          fileName: 'Transfer_API_Swagger_Spec.docx',
          fileSize: '840 KB',
          uploadedBy: 'David Chen',
          uploadedAt: '2026-08-12',
          version: 'v2.4.1',
          downloadUrl: '#',
        },
      ],
      figmaUrl: 'https://www.figma.com/file/aegis-banking-superapp-hifi/v2.4',
      figmaName: 'SuperApp Design System & Transfer Flow v2.4',
      figmaDescription: 'Full mobile and responsive web frames with auto-layout padding tokens.',
      figmaVersion: '2.4.0',
      figmaPreviewTitle: 'SuperApp UI Kit & Interactive Transfer Flows (Figma v2.4)',
      requirements: [
        'REQ-101: Biometric Authentication with Secure Enclave',
        'REQ-102: Instant Wire Transfer with Idempotency Key',
        'REQ-103: Dynamic Fee calculation based on KYC Tier',
        'REQ-104: Timeout resilience & transaction rollback protection',
        'REQ-105: Real-time push notification and statement export',
      ],
      testEnvUrl: 'https://staging-app.bankingsuperapp.internal',
      repoUrl: 'https://github.com/bankcorp/superapp-client',
      buildVersion: 'v2.4.0-rc3',
      apiDocUrl: 'https://api-docs.bankcorp.internal/v2/swagger',
      testCredentials: [
        { role: 'Standard Tier Tester', user: 'qa.standard@bank.internal', pass: 'SecurePass!2026', notes: 'Pre-seeded balance: $12,500 USD' },
        { role: 'VIP Tier Tester', user: 'qa.vip@bank.internal', pass: 'GoldTier#999', notes: 'Pre-seeded balance: $150,000 USD (0% fees)' },
        { role: 'Blocked KYC Tester', user: 'qa.restricted@bank.internal', pass: 'KycHold$444', notes: 'Should trigger KYC re-verification banner' },
      ],
      releaseInfo: 'Candidate build 2.4.0-rc3. Regression sign-off window closes Sep 10, 18:00 UTC.',
      importantNotes: 'Staging API payment gateway sandbox undergoes maintenance between 02:00-04:00 UTC.',
    },
  },
  {
    id: 'prj-mobile',
    name: 'Mobile Banking iOS & Android',
    description: 'Cross-platform native mobile client focusing on card management, contactless NFC payments, and push security tokens.',
    status: 'UAT',
    startDate: '2026-07-15',
    targetReleaseDate: '2026-09-18',
    projectOwner: 'Elena Rostova (Mobile Director)',
    qaLeadId: 'usr-sarah',
    memberIds: ['usr-hana', 'usr-sara'],
    qaProgress: 81,
    regressionProgress: 78,
    resources: {
      prdTitle: 'PRD Mobile v3.1: Virtual Card Issuance & NFC',
      prdUrl: 'https://docs.bankcorp.internal/prd/mobile-v3.1',
      prdContent: `# Mobile Banking v3.1 Specifications\nSupport Apple Pay and Google Wallet instant push provisioning. Card freeze/unfreeze toggle with sub-second feedback.`,
      figmaUrl: 'https://www.figma.com/file/aegis-mobile-cards/v3.1',
      figmaName: 'Mobile Cards & Wallet Flow v3.1',
      figmaDescription: 'Native iOS & Android card views with encrypted CVV reveal.',
      figmaVersion: '3.1.0',
      figmaPreviewTitle: 'Mobile Native Components & Virtual Card Flow',
      requirements: [
        'REQ-M01: Virtual card generation within 2 seconds',
        'REQ-M02: Apple Wallet / Google Wallet provisioning',
        'REQ-M03: Instant card locking and geo-fencing controls',
      ],
      testEnvUrl: 'https://mobile-stage.bankingsuperapp.internal',
      repoUrl: 'https://github.com/bankcorp/mobile-native',
      buildVersion: 'build-412',
      apiDocUrl: 'https://api-docs.bankcorp.internal/mobile/v3',
      testCredentials: [
        { role: 'Mobile Beta User', user: 'qa.mobile.tester@bank.internal', pass: 'Mob@2026Safe', notes: 'Enrolled in NFC pilot sandbox' },
      ],
      releaseInfo: 'TestFlight build #412 / Internal App Distribution #208.',
      importantNotes: 'Test specifically on iOS 18.0 and Android 15 developer previews.',
    },
  },
  {
    id: 'prj-merchant',
    name: 'Merchant Portal NextGen',
    description: 'B2B web dashboard for e-commerce and retail merchants to manage settlements, chargebacks, and API webhook integrations.',
    status: 'Planning',
    startDate: '2026-08-20',
    targetReleaseDate: '2026-10-05',
    projectOwner: 'Marcus Vance (Fintech Ops)',
    qaLeadId: 'usr-sarah',
    memberIds: ['usr-sara', 'usr-ahmed'],
    qaProgress: 35,
    regressionProgress: 15,
    resources: {
      prdTitle: 'PRD Merchant Portal v1.0: Real-time Analytics & Dispute Center',
      prdUrl: 'https://docs.bankcorp.internal/prd/merchant-portal-v1',
      prdContent: `# Merchant Portal v1.0 PRD\nUnified settlement report download in CSV/XLSX. Automated webhook delivery with retry backoff.`,
      figmaUrl: 'https://www.figma.com/file/aegis-merchant-v1/design',
      figmaName: 'Merchant Portal v1.0 Web App',
      figmaDescription: 'Full B2B desktop dashboard and dispute evidence modal.',
      figmaVersion: '1.0.0',
      figmaPreviewTitle: 'Merchant B2B Dashboard Layout & Dispute Flow',
      requirements: [
        'REQ-B01: Dispute evidence upload supporting up to 25MB PDF/PNG',
        'REQ-B02: Webhook signature verification tool for merchants',
      ],
      testEnvUrl: 'https://staging-merchant.bankingsuperapp.internal',
      repoUrl: 'https://github.com/bankcorp/merchant-web',
      buildVersion: 'v1.0.0-alpha2',
      apiDocUrl: 'https://api-docs.bankcorp.internal/merchant/v1',
      testCredentials: [
        { role: 'Merchant Admin', user: 'admin@coffeehaven.com', pass: 'CoffeeB2B@99!', notes: 'Connected to mock Stripe & Adyen test rails' },
      ],
      releaseInfo: 'Alpha testing phase. Architecture and test plan sign-off.',
      importantNotes: 'Backend services still in active deployment.',
    },
  },
];

export const INITIAL_TASKS: QATask[] = [
  {
    id: 'tsk-101',
    title: 'Test Payment API Endpoints',
    description: 'Execute integration tests on /api/v2/transfers, validate idempotency headers, schema validation, and error codes (400, 401, 409, 504).',
    projectId: 'prj-banking',
    module: 'Payment API',
    assigneeId: 'usr-hana',
    priority: 'High',
    estimatedEffortHours: 6,
    actualEffortHours: 4,
    dueDate: '2026-09-05',
    status: 'In Progress',
    relatedRequirement: 'REQ-102: Instant Wire Transfer',
    relatedTestCaseId: 'tc-201',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-05',
  },
  {
    id: 'tsk-102',
    title: 'Retest BUG-142: Payment Gateway 500 error on zero-decimal currencies',
    description: 'Verify fix on staging build rc3. Ensure JPY and KRW transactions do not fail on decimal parsing.',
    projectId: 'prj-banking',
    module: 'Payment Module',
    assigneeId: 'usr-hana',
    priority: 'Critical',
    estimatedEffortHours: 2,
    actualEffortHours: 0,
    dueDate: '2026-09-05',
    status: 'Assigned',
    relatedRequirement: 'REQ-102: Instant Wire Transfer',
    relatedBugId: 'bug-142',
    createdAt: '2026-09-04',
    updatedAt: '2026-09-05',
  },
  {
    id: 'tsk-103',
    title: 'Validate Figma Implementation for Payment Flow',
    description: 'Cross-reference Staging web UI with Figma design v2.4 frames. Check responsive breakpoints, dark mode token contrast, and micro-interactions.',
    projectId: 'prj-banking',
    module: 'UI/UX Verification',
    assigneeId: 'usr-hana',
    priority: 'Medium',
    estimatedEffortHours: 4,
    dueDate: '2026-09-07',
    status: 'Backlog',
    relatedRequirement: 'REQ-103: Dynamic Fee Display',
    createdAt: '2026-09-03',
    updatedAt: '2026-09-04',
  },
  {
    id: 'tsk-104',
    title: 'Execute Regression for Login & Biometrics Module',
    description: 'Run full regression suite for FaceID, fingerprint, pin authorization, and lockout after 3 failed attempts.',
    projectId: 'prj-banking',
    module: 'Authentication',
    assigneeId: 'usr-ahmed',
    priority: 'Critical',
    estimatedEffortHours: 8,
    actualEffortHours: 6,
    dueDate: '2026-09-06',
    status: 'In Progress',
    relatedRequirement: 'REQ-101: Biometric Authorization',
    relatedTestCaseId: 'tc-101',
    createdAt: '2026-09-01',
    updatedAt: '2026-09-04',
  },
  {
    id: 'tsk-105',
    title: 'Execute Payment Regression Suite',
    description: 'Perform complete end-to-end regression across all wire transfer scenarios, VIP tier rules, and currency conversions.',
    projectId: 'prj-banking',
    module: 'Payment Module',
    assigneeId: 'usr-ahmed',
    priority: 'Critical',
    estimatedEffortHours: 8,
    dueDate: '2026-09-07',
    status: 'Assigned',
    relatedRequirement: 'REQ-102 & REQ-104',
    createdAt: '2026-09-03',
    updatedAt: '2026-09-04',
  },
  {
    id: 'tsk-106',
    title: 'Retest BUG-124: Token refresh loop on session timeout',
    description: 'Validate refresh token rotation logic when user leaves app open in background for 30 minutes.',
    projectId: 'prj-banking',
    module: 'Authentication',
    assigneeId: 'usr-ahmed',
    priority: 'High',
    estimatedEffortHours: 3,
    dueDate: '2026-09-06',
    status: 'Assigned',
    relatedBugId: 'bug-124',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-04',
  },
  {
    id: 'tsk-107',
    title: 'Mobile Virtual Card Generation Test Suite',
    description: 'Run native iOS & Android test cases for instant debit card issuance and encrypted CVV reveal.',
    projectId: 'prj-mobile',
    module: 'Cards',
    assigneeId: 'usr-sara',
    priority: 'High',
    estimatedEffortHours: 5,
    actualEffortHours: 3,
    dueDate: '2026-09-06',
    status: 'In Progress',
    relatedRequirement: 'REQ-M01: Virtual Card Issuance',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-04',
  },
  {
    id: 'tsk-108',
    title: 'KYC Document Upload Edge Cases & OCR Validation',
    description: 'Test passport, national ID, and driver license uploads under various lighting and blur conditions.',
    projectId: 'prj-banking',
    module: 'KYC / Onboarding',
    assigneeId: 'usr-daniel',
    priority: 'Critical',
    estimatedEffortHours: 7,
    dueDate: '2026-09-06',
    status: 'Blocked',
    notes: 'Blocked by third-party OCR sandbox outage.',
    relatedRequirement: 'REQ-105: KYC Compliance',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-05',
  },
];

export const INITIAL_BUGS: QABug[] = [
  {
    id: 'bug-142',
    title: 'Payment Gateway 500 error on zero-decimal currencies (JPY, KRW)',
    description: 'When initiating transfer in JPY, backend divides amount by 100 causing decimal precision rejection in core ledger.',
    projectId: 'prj-banking',
    module: 'Payment Module',
    environment: 'Staging App v2.4-rc3',
    buildVersion: 'v2.4.0-rc3',
    severity: 'Critical',
    priority: 'Critical',
    status: 'Retest',
    reporterId: 'usr-hana',
    assigneeId: 'usr-hana',
    stepsToReproduce: [
      'Login as Standard QA Tester',
      'Select Transfer -> International -> Currency JPY',
      'Enter amount 5000 JPY',
      'Submit transfer',
    ],
    expectedResult: 'Transfer completes with fee conversion and whole integer ledger record.',
    actualResult: 'HTTP 500 Internal Server Error: Ledger decimal constraint violated: 50.00 JPY',
    createdAt: '2026-09-03',
    updatedAt: '2026-09-04',
    lastActivityAt: '2026-09-04',
    reopenedCount: 1,
    relatedRequirement: 'REQ-102',
  },
  {
    id: 'bug-140',
    title: 'KYC Document upload silently fails on high-resolution PNGs (>12MB)',
    description: 'Camera uploads on iPhone 15 Pro Max freeze at 99% progress bar without user-facing error message.',
    projectId: 'prj-banking',
    module: 'KYC / Onboarding',
    environment: 'iOS 18 TestFlight #412',
    buildVersion: 'build-412',
    severity: 'Critical',
    priority: 'Critical',
    status: 'In Progress',
    reporterId: 'usr-daniel',
    assigneeId: 'usr-daniel',
    stepsToReproduce: [
      'Initiate KYC Verification',
      'Choose passport photo from gallery (14MB PNG)',
      'Tap submit',
    ],
    expectedResult: 'App compresses image client-side or shows file size limit toast.',
    actualResult: 'Upload spinner spins indefinitely; memory exceeds 800MB and app crashes.',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-03',
    lastActivityAt: '2026-09-03',
    reopenedCount: 0,
  },
  {
    id: 'bug-138',
    title: 'Biometric authorization modal does not dismiss after FaceID timeout',
    description: 'Leaving FaceID prompt open until OS timeout leaves modal overlay permanently stuck.',
    projectId: 'prj-banking',
    module: 'Authentication',
    environment: 'iOS 18 Staging',
    buildVersion: 'v2.4.0-rc3',
    severity: 'Critical',
    priority: 'Critical',
    status: 'Open',
    reporterId: 'usr-ahmed',
    assigneeId: 'usr-ahmed',
    stepsToReproduce: [
      'Enable FaceID in Settings',
      'Trigger payment authorization',
      'Cover front camera and wait 15 seconds',
    ],
    expectedResult: 'FaceID fallback to PIN prompt appears.',
    actualResult: 'Blank gray sheet locks the screen; user must force-quit app.',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-03',
    lastActivityAt: '2026-09-03',
    reopenedCount: 0,
    relatedRequirement: 'REQ-101',
  },
  {
    id: 'bug-124',
    title: 'Infinite redirect loop on expired refresh token during payment submission',
    description: 'If token expires while transfer confirmation modal is open, user is redirected between /login and /transfer.',
    projectId: 'prj-banking',
    module: 'Authentication',
    environment: 'Staging Web',
    buildVersion: 'v2.4.0-rc2',
    severity: 'High',
    priority: 'High',
    status: 'Retest',
    reporterId: 'usr-ahmed',
    assigneeId: 'usr-ahmed',
    stepsToReproduce: [
      'Open transfer modal',
      'Manually delete access_token cookie in DevTools',
      'Wait for background poll',
    ],
    expectedResult: 'Clean session expiry dialog offering re-authentication.',
    actualResult: 'Browser flashes between routes and exhausts call stack.',
    createdAt: '2026-09-01',
    updatedAt: '2026-09-04',
    lastActivityAt: '2026-09-04',
    reopenedCount: 0,
  },
  {
    id: 'bug-119',
    title: 'Transfer fee incorrectly charged to VIP tier users in cross-border wire',
    description: 'Dynamic fee calculation bypasses VIP exemption flag when destination country is UK (GBP).',
    projectId: 'prj-banking',
    module: 'Payment Module',
    environment: 'Staging App v2.4-rc3',
    buildVersion: 'v2.4.0-rc3',
    severity: 'High',
    priority: 'High',
    status: 'In Progress',
    reporterId: 'usr-hana',
    assigneeId: 'usr-hana',
    stepsToReproduce: [
      'Login as qa.vip@bank.internal',
      'Transfer $5,000 USD to GBP account',
      'Inspect summary screen',
    ],
    expectedResult: 'Fee displayed: $0.00 (VIP Privilege).',
    actualResult: 'Fee displayed: $15.00 international wire fee.',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-04',
    lastActivityAt: '2026-09-04',
    reopenedCount: 1,
    relatedRequirement: 'REQ-103',
  },
];

export const INITIAL_TEST_SUITES: TestSuite[] = [
  {
    id: 'ts-auth',
    projectId: 'prj-banking',
    title: 'Authentication & Biometrics Suite',
    description: 'FaceID, PIN fallback, lockout thresholds, and session security.',
    module: 'Authentication',
  },
  {
    id: 'ts-transfers',
    projectId: 'prj-banking',
    title: 'Instant Wire Transfers & Idempotency',
    description: 'P2P payments, idempotency collision, VIP fee waivers, and timeout recovery.',
    module: 'Payment API',
  },
  {
    id: 'ts-cards',
    projectId: 'prj-mobile',
    title: 'Mobile Virtual Cards & NFC Provisioning',
    description: 'Card activation, CVV encryption, and wallet sync.',
    module: 'Cards',
  },
];

export const INITIAL_TEST_CASES: TestCase[] = [
  {
    id: 'tc-101',
    suiteId: 'ts-auth',
    projectId: 'prj-banking',
    title: 'Verify Biometric FaceID authentication with valid face match',
    module: 'Authentication',
    steps: [
      { stepNumber: 1, action: 'Trigger FaceID prompt during login', expectedResult: 'OS Biometric sheet appears' },
      { stepNumber: 2, action: 'Provide valid biometric vector', expectedResult: 'Instant token generation and redirect to dashboard' },
    ],
    expectedResult: 'User authenticated in under 400ms without password prompt.',
    priority: 'Critical',
    type: 'Regression',
    author: 'Ahmed Al-Mansoor',
    status: 'Active',
    requirement: 'REQ-101',
    assigneeId: 'usr-ahmed',
    executionStatus: 'Passed',
    lastExecutedAt: '2026-09-04',
    lastExecutedBy: 'usr-ahmed',
  },
  {
    id: 'tc-102',
    suiteId: 'ts-auth',
    projectId: 'prj-banking',
    title: 'Verify Account Lockout after 3 consecutive failed biometric attempts',
    module: 'Authentication',
    steps: [
      { stepNumber: 1, action: 'Fail biometric verification 3 times consecutively', expectedResult: 'Cool-off countdown initiated' },
      { stepNumber: 2, action: 'Attempt immediate 4th login', expectedResult: 'Login disabled with 5-minute lockout message' },
    ],
    expectedResult: 'System enforces 5-minute cooldown banner and notifies user via email.',
    priority: 'Critical',
    type: 'Security Testing' as any,
    author: 'Sarah Jenkins',
    status: 'Active',
    requirement: 'REQ-101',
    assigneeId: 'usr-ahmed',
    executionStatus: 'Passed',
    lastExecutedAt: '2026-09-04',
    lastExecutedBy: 'usr-ahmed',
  },
  {
    id: 'tc-201',
    suiteId: 'ts-transfers',
    projectId: 'prj-banking',
    title: 'Verify Idempotency Key prevents duplicate transfer on double-tap',
    module: 'Payment API',
    steps: [
      { stepNumber: 1, action: 'Send POST /transfers with Idempotency-Key: test-uuid-001', expectedResult: 'Transfer initiated (200 OK)' },
      { stepNumber: 2, action: 'Repeat exact same request within 3 seconds', expectedResult: 'HTTP 409 Conflict with original receipt ID' },
    ],
    expectedResult: 'Account balance deducted exactly once; single transfer receipt generated.',
    priority: 'Critical',
    type: 'API',
    author: 'Hana Kim',
    status: 'Active',
    requirement: 'REQ-102',
    assigneeId: 'usr-hana',
    executionStatus: 'Blocked',
    executionNotes: 'Blocked due to payment sandbox mock environment outage.',
    lastExecutedAt: '2026-09-05',
    lastExecutedBy: 'usr-hana',
  },
  {
    id: 'tc-202',
    suiteId: 'ts-transfers',
    projectId: 'prj-banking',
    title: 'Verify VIP tier user incurs 0% fee on international wire transfer',
    module: 'Payment API',
    steps: [
      { stepNumber: 1, action: 'Authenticate as qa.vip@bank.internal', expectedResult: 'VIP status badge active' },
      { stepNumber: 2, action: 'Submit $10,000 USD to EUR transfer', expectedResult: 'Fee breakdown shows $0.00 fee waiver' },
    ],
    expectedResult: 'Total deducted equals principal amount with zero additional fees.',
    priority: 'High',
    type: 'Functional',
    author: 'Hana Kim',
    status: 'Active',
    requirement: 'REQ-103',
    assigneeId: 'usr-hana',
    executionStatus: 'Failed',
    linkedBugId: 'bug-119',
    executionNotes: 'Failed: Fee calculation still adds $15 fee for GBP and EUR (BUG-119).',
    lastExecutedAt: '2026-09-04',
    lastExecutedBy: 'usr-hana',
  },
  {
    id: 'tc-301',
    suiteId: 'ts-cards',
    projectId: 'prj-mobile',
    title: 'Verify Virtual Debit Card generation in under 2 seconds',
    module: 'Cards',
    steps: [
      { stepNumber: 1, action: 'Tap Create Virtual Card on iOS client', expectedResult: 'Card animation triggers' },
      { stepNumber: 2, action: 'Verify card details returned', expectedResult: 'Encrypted PAN, CVV, and expiry displayed' },
    ],
    expectedResult: 'Virtual card created in 1.4s and available for immediate Apple Pay export.',
    priority: 'High',
    type: 'UI',
    author: 'Sara Vance',
    status: 'Active',
    requirement: 'REQ-M01',
    assigneeId: 'usr-sara',
    executionStatus: 'Passed',
    lastExecutedAt: '2026-09-04',
    lastExecutedBy: 'usr-sara',
  },
];

export const INITIAL_REGRESSION_CYCLES: RegressionCycle[] = [
  {
    id: 'reg-01',
    projectId: 'prj-banking',
    title: 'Sprint 24 Core Regression Cycle',
    buildVersion: 'v2.4.0-rc3',
    environment: 'Staging Web & iOS',
    startDate: '2026-09-01',
    endDate: '2026-09-10',
    assignedMemberIds: ['usr-ahmed', 'usr-hana'],
    testCaseIds: ['tc-101', 'tc-102', 'tc-201', 'tc-202'],
    status: 'In Progress',
    passRate: 62,
    createdAt: '2026-09-01',
  },
  {
    id: 'reg-02',
    projectId: 'prj-mobile',
    title: 'Mobile NFC & Wallet Regression Test Run',
    buildVersion: 'build-412',
    environment: 'TestFlight iOS 18',
    startDate: '2026-09-03',
    endDate: '2026-09-12',
    assignedMemberIds: ['usr-sara'],
    testCaseIds: ['tc-301'],
    status: 'In Progress',
    passRate: 100,
    createdAt: '2026-09-03',
  },
];

export const INITIAL_BLOCKERS: Blocker[] = [
  {
    id: 'blk-01',
    title: 'Staging API payment gateway sandbox mock returning 502 Bad Gateway',
    description: 'Third-party mock service sandbox crashed on staging. Blocks wire transfer idempotency testing.',
    projectId: 'prj-banking',
    taskId: 'tsk-101',
    memberId: 'usr-hana',
    severity: 'Critical',
    status: 'Investigating',
    createdAt: '2026-09-04',
  },
  {
    id: 'blk-02',
    title: 'Device farm timeout issues on Android 14 emulators',
    description: 'Test runner stalls after 5 test executions requiring manual session reboot by IT.',
    projectId: 'prj-banking',
    taskId: 'tsk-108',
    memberId: 'usr-daniel',
    severity: 'High',
    status: 'Waiting',
    createdAt: '2026-09-03',
  },
];

export const INITIAL_DAILY_REPORTS: DailyReport[] = [
  {
    id: 'rep-hana-yesterday',
    date: '2026-09-04',
    memberId: 'usr-hana',
    projectId: 'prj-banking',
    yesterdayCompleted: 'Completed login integration testing and executed 12 test cases.',
    todayWorkingOn: 'Execute Payment API endpoint test suite and retest BUG-142.',
    isBlocked: true,
    blockers: 'Staging API payment sandbox became unresponsive at 16:00 UTC.',
    progressPercentage: 65,
    expectedCompletion: 'Today',
    notes: 'DevOps is investigating the sandbox proxy gateway.',
    status: 'submitted',
    submittedAt: '2026-09-04T17:30:00Z',
  },
  {
    id: 'rep-ahmed-yesterday',
    date: '2026-09-04',
    memberId: 'usr-ahmed',
    projectId: 'prj-banking',
    yesterdayCompleted: 'Automated 8 login biometric regression scenarios. Passed authentication suite.',
    todayWorkingOn: 'Begin full Payment Regression and retest BUG-124.',
    isBlocked: false,
    blockers: '',
    progressPercentage: 50,
    expectedCompletion: 'Tomorrow',
    notes: 'Need assistance with payment regression test execution load.',
    status: 'submitted',
    submittedAt: '2026-09-04T18:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    recipientId: 'usr-hana',
    title: '📋 New QA Project Assignment',
    message: 'You have been assigned to: Banking SuperApp.\nQA Lead: Sarah Jenkins.\nResources: 📄 PRD, 🎨 Figma.\nPlease review project documentation before starting testing.',
    type: 'assignment',
    read: false,
    createdAt: '2026-09-05T08:00:00Z',
    actionUrl: 'projects',
  },
  {
    id: 'notif-02',
    recipientId: 'usr-hana',
    title: 'Task Approaching Deadline',
    message: 'Payment API Testing is due today (Sep 05). Please submit status or update blockers.',
    type: 'deadline',
    read: false,
    createdAt: '2026-09-05T08:15:00Z',
  },
  {
    id: 'notif-03',
    recipientId: 'usr-sarah',
    title: '⚠️ Blocker Reported: Staging API sandbox 502',
    message: 'Hana Kim reported a Critical blocker on Banking SuperApp.',
    type: 'blocker_created',
    read: false,
    createdAt: '2026-09-05T08:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    timestamp: '2026-09-04 18:05:12',
    actorId: 'usr-sarah',
    actorName: 'Sarah Jenkins',
    actorRole: 'qa_lead',
    action: 'Task Priority Updated',
    entityType: 'task',
    entityId: 'tsk-102',
    previousValue: 'High',
    newValue: 'Critical',
  },
  {
    id: 'aud-02',
    timestamp: '2026-09-04 17:30:22',
    actorId: 'usr-hana',
    actorName: 'Hana Kim',
    actorRole: 'qa_engineer',
    action: 'Daily Report Submitted',
    entityType: 'report',
    entityId: 'rep-hana-yesterday',
    previousValue: 'draft',
    newValue: 'submitted',
  },
  {
    id: 'aud-03',
    timestamp: '2026-09-05 08:31:00',
    actorId: 'usr-hana',
    actorName: 'Hana Kim',
    actorRole: 'qa_engineer',
    action: 'Reported Blocker',
    entityType: 'blocker',
    entityId: 'blk-01',
    newValue: 'Staging API payment gateway sandbox mock returning 502 Bad Gateway',
  },
];
